### PR TITLE
connection: add an errors counter

### PR DESCRIPTION
**Pull request by msimerson**
that counts a bunch of errors that unrecognized doesn't

### CODE REVIEW

**Comment by smfreegard** [comment]
Why don't you increment this counter on an unhandled unrecognized command as well?  Then there's no need to count these in the hook.

I'd also add this counter to the disconnect log line.

**Comment by msimerson** [comment]
> Why don't you increment this counter on an unhandled unrecognized command as well?

Oversight, and I'm not sure how to identify that an unrecognized command was not handled. Where would I detect that?

**Comment by smfreegard** [comment]
Adding it here: https://github.com/baudehlo/Haraka/blob/master/connection.js#L677 should do it.

Nice catch on this one - I'd forgotten that there were a bunch of placed that did this.

**Comment by msimerson** [comment]
PR updated as requested, and squashed.

**Pull request merged**
