### PR TITLE
Handle IPv6 in is_rfc1918 - fixes #850

### LINKED ISSUE #850: Error: Outbound email with "auth/flat_file"
=== Connected to localhost.
<-  220 li940-16 ESMTP Haraka 2.5.0 ready
 -> EHLO li940-16.members.linode.com
<-  250-li940-16 Hello ip6-localhost [::1], Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250 SIZE 500000
*** Host did not advertise authentication
 -> QUIT
<-  221 li940-16 closing connection. Have a jolly good day.
=== Connection closed with remote host.

Please any one help me on this...

Thanks,
Varma

### PR DESCRIPTION
**Pull request by smfreegard**

### CODE REVIEW

**Comment by msimerson** [comment]
Does anyone else think it's a bit wrong to be shoehorning IPv6 into a function containing the name `rfc1918`?  In 1996, IPv6 was just a glint in Vint's eye. I'd prefer to leave is_rfc1918 defined by RFC 1918, and instead add new IPv4 & IPv6 capable functions that suit the common use cases of a SMTP server. Example methods:

* is_private_ipv4  (10/8, 172.16/12, 192.168/16)    (RFC 1918)
* is_local_net (0.0.0.0/8, 127/8, ::1)                        (RFC 1122)
* is_link_local (169.254.0.0/16, fe80::/10)                (RFC 3927, 4862)
* is_private  ( is_private_ipv4 || is_local_net || is_link_local )

There's plenty of other net blocks in the [Special Purpose IP Registry](https://tools.ietf.org/html/rfc6890) and we could likely be handling more intelligently, but that's likely an issue of it's very own. For now,

**Comment by msimerson** [comment]
@smfreegard , have a look at commit [e9c4579e](https://github.com/smfreegard/Haraka/commit/e9c4579e2eb8a2b38d897eb0b98fa7d5f783c724). You do realize that if this branch is merged to baudehlo/master, then all the history in that commit is getting duplicated in the main repo?  It really makes a mess in the commit logs and it's rather confusing to find a half dozen commits that all make exactly the same thing. The solution is to use git rebase instead of git merge in your branches. `git pull && git rebase -i` will tidy it up.

**Comment by baudehlo** [comment]
Ultimately I think bickering about the name of the function is pretty pointless. It's used to see if something is a local network everywhere within Haraka. If we have future use-case where we need to split it up more fine grained then we can do so.

For now, I'm sure it's fine. A bit of docs I'm sure could say what it really does. But nothing worth doing until after we get 2.6 out.

**Comment by msimerson** [comment]
Thinking out loud here, I wonder if squashing this branch would also get rid of that merge commit?

**Pull request closed without merging**
