### PR TITLE
configfile: shed some excess indention

### PR DESCRIPTION
**Pull request by msimerson**
* replace cfreader.config_path with cp (5x)
* early exit of functions permit removing of extra indention

### CODE REVIEW

**Comment by baudehlo** [comment]
That's a rather large diff for a straight pull-merge while we're supposed to be in code freeze... Do we have enough test coverage of that area of code to know it's working the same in all conditions?

**Comment by msimerson** [comment]
The diff size is primarily the result of the "left shift" of those two blocks by 4 spaces. I wonder if, in cases like this, if wouldn't be better (for the purposes of review at least) to make the 2-3 line changes that permit the left shift in one PR, and then follow it with the left shifted block in another. I'm betting that github's whitespace highlighting would then work and it wouldn't **appear** be a substantive change.

**Comment by msimerson** [comment]
Actually, using two PRs wouldn't be necessary. Two commits in one PR, with a note explaining that the code change is in the first, and the second is **only** a left shift that happens to balloon the diff in rude proportion ought to work...

**Comment by baudehlo** [comment]
Yeah I only commented because there's a bit of a logic change (or reversal)
to make the indent change, and I was too tired to be able to take in the
entire thing.

**Pull request merged**
