### PR TITLE
New backscatterer plugin

### PR DESCRIPTION
**Pull request by smfreegard**
Useful little plugin; has a fairly high crossover with Zen/Spamcop at times, but generally works pretty well and I've found it pretty safe to reject outright with.

`````
msg="Host DNSERROR [202.56.255.50] is blacklisted by ips.backscatterer.org"
msg="Host c-73-132-35-70.hsd1.va.comcast.net [73.132.35.70] is blacklisted by ips.backscatterer.org"
msg="Host 135-13.alba.dp.ua [193.151.13.135] is blacklisted by ips.backscatterer.org"
msg="Host bas5-toronto01-1177868522.dsl.bell.ca [70.52.216.234] is blacklisted by ips.backscatterer.org"
msg="Host dsl-201-114-84-32-dyn.prod-infinitum.com.mx [201.114.84.32] is blacklisted by ips.backscatterer.org"
msg="Host bba598780.alshamil.net.ae [86.98.78.102] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [77.67.227.244] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [188.211.124.52] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [212.200.102.6] is blacklisted by ips.backscatterer.org"
msg="Host 93-79-109-73.sumy.volia.net [93.79.109.73] is blacklisted by ips.backscatterer.org"
msg="Host mm-198-10-125-178.mfilial.dynamic.pppoe.byfly.by [178.125.10.198] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [92.84.97.111] is blacklisted by ips.backscatterer.org"
msg="Host 2.134.73.232.megaline.telecom.kz [2.134.73.232] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [116.105.197.189] is blacklisted by ips.backscatterer.org"
msg="Host 85-210-157-74.dynamic.dsl.as9105.com [85.210.157.74] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [109.102.173.79] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [5.76.34.28] is blacklisted by ips.backscatterer.org"
msg="Host bba588583.alshamil.net.ae [86.98.41.65] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [62.89.21.73] is blacklisted by ips.backscatterer.org"
msg="Host 5e0ba18d.bb.sky.com [94.11.161.141] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [92.83.96.40] is blacklisted by ips.backscatterer.org"
msg="Host broadband-5-228-231-119.nationalcablenetworks.ru [5.228.231.119] is blacklisted by ips.backscatterer.org"
msg="Host 115.118.169.51.static-ttsl-hyderabad.vsnl.net.in [115.118.169.51] is blacklisted by ips.backscatterer.org"
msg="Host triband-mum-120.60.143.77.mtnl.net.in [120.60.143.77] is blacklisted by ips.backscatterer.org"
msg="Host cable-181-133-137-60.une.net.co [181.133.137.60] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [80.69.50.104] is blacklisted by ips.backscatterer.org"
msg="Host 94-159-174-79.orange.net.il [94.159.174.79] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [115.178.26.178] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [58.211.129.90] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [117.206.97.90] is blacklisted by ips.backscatterer.org"
msg="Host localhost [113.181.59.230] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [197.225.30.251] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [171.224.125.43] is blacklisted by ips.backscatterer.org"
msg="Host localhost [117.7.160.203] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [62.89.30.220] is blacklisted by ips.backscatterer.org"
msg="Host 176-119-104-7.broadband.tenet.odessa.ua [176.119.104.7] is blacklisted by ips.backscatterer.org"
msg="Host user-5-173-86-66.play-internet.pl [5.173.86.66] is blacklisted by ips.backscatterer.org"
msg="Host 176-119-105-234.broadband.tenet.odessa.ua [176.119.105.234] is blacklisted by ips.backscatterer.org"
msg="Host m15-153.126.com [220.181.15.153] is blacklisted by ips.backscatterer.org"
msg="Host cpe-108-184-46-188.socal.res.rr.com [108.184.46.188] is blacklisted by ips.backscatterer.org"
msg="Host cust-251-184.on1.ontelecoms.gr [91.132.251.184] is blacklisted by ips.backscatterer.org"
msg="Host bzq-79-178-179-48.red.bezeqint.net [79.178.179.48] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [46.109.196.78] is blacklisted by ips.backscatterer.org"
msg="Host dynamic-87-105-67-186.ssp.dialog.net.pl [87.105.67.186] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [93.79.140.248] is blacklisted by ips.backscatterer.org"
msg="Host client.fttb.2day.kz [176.222.188.93] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [5.178.237.153] is blacklisted by ips.backscatterer.org"
msg="Host adsl-ull-27-254.49-151.net24.it [151.49.254.27] is blacklisted by ips.backscatterer.org"
msg="Host 89-73-13-215.dynamic.chello.pl [89.73.13.215] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [59.90.188.12] is blacklisted by ips.backscatterer.org"
msg="Host dsl-189-132-25-232-dyn.prod-infinitum.com.mx [189.132.25.232] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [121.28.182.182] is blacklisted by ips.backscatterer.org"
msg="Host dslb-088-067-225-201.088.067.pools.vodafone-ip.de [88.67.225.201] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [80.77.136.65] is blacklisted by ips.backscatterer.org"
msg="Host a95-95-97-119.cpe.netcabo.pt [95.95.97.119] is blacklisted by ips.backscatterer.org"
msg="Host dsl-187-214-78-11-dyn.prod-infinitum.com.mx [187.214.78.11] is blacklisted by ips.backscatterer.org"
msg="Host static-57-236-235-87.ipcom.comunitel.net [87.235.236.57] is blacklisted by ips.backscatterer.org"
msg="Host daw013-116578.routed.opal-solutions.com [164.40.214.129] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [37.211.77.1] is blacklisted by ips.backscatterer.org"
msg="Host static091138185238.access.hol.gr [91.138.185.238] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [171.249.172.7] is blacklisted by ips.backscatterer.org"
msg="Host 164.73.30.213.rev.vodafone.pt [213.30.73.164] is blacklisted by ips.backscatterer.org"
msg="Host 63-158-224-118.dia.static.qwest.net [63.158.224.118] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [116.100.67.124] is blacklisted by ips.backscatterer.org"
msg="Host cpe-74-73-44-87.nyc.res.rr.com [74.73.44.87] is blacklisted by ips.backscatterer.org"
msg="Host net1-customer166.adrana.ro [37.143.160.166] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [92.84.168.32] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [78.95.253.86] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [41.214.149.29] is blacklisted by ips.backscatterer.org"
msg="Host agadadiabetes.net [115.249.155.250] is blacklisted by ips.backscatterer.org"
msg="Host cable-89-216-193-101.dynamic.sbb.rs [89.216.193.101] is blacklisted by ips.backscatterer.org"
msg="Host 84-55-125-145.customers.ownit.se [84.55.125.145] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [178.172.246.208] is blacklisted by ips.backscatterer.org"
msg="Host host-92-17-214-217.as13285.net [92.17.214.217] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [109.101.117.48] is blacklisted by ips.backscatterer.org"
msg="Host user-164-126-231-40.play-internet.pl [164.126.231.40] is blacklisted by ips.backscatterer.org"
msg="Host LNeuilly-152-21-5-80.w193-253.abo.wanadoo.fr [193.253.36.80] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [91.237.242.98] is blacklisted by ips.backscatterer.org"
msg="Host m15-155.126.com [220.181.15.155] is blacklisted by ips.backscatterer.org"
msg="Host host3-20-static.91-82-b.business.telecomitalia.it [82.91.20.3] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [36.83.41.73] is blacklisted by ips.backscatterer.org"
msg="Host localhost [113.170.50.178] is blacklisted by ips.backscatterer.org"
msg="Host m15-151.126.com [220.181.15.151] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [105.158.78.148] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [121.168.217.204] is blacklisted by ips.backscatterer.org"
msg="Host a89-155-192-26.cpe.netcabo.pt [89.155.192.26] is blacklisted by ips.backscatterer.org"
msg="Host 108-235-30-78.host.sevstar.net [78.30.235.108] is blacklisted by ips.backscatterer.org"
msg="Host 114-26-45-158.dynamic.hinet.net [114.26.45.158] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [185.5.154.206] is blacklisted by ips.backscatterer.org"
msg="Host 95.9.238.179.static.ttnet.com.tr [95.9.238.179] is blacklisted by ips.backscatterer.org"
msg="Host data-153-235.cgates.lt [5.20.153.235] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [211.99.189.68] is blacklisted by ips.backscatterer.org"
msg="Host 72-239-10-1.res.bhn.net [72.239.10.1] is blacklisted by ips.backscatterer.org"
msg="Host 144.7.180.213.sta.estpak.ee [213.180.7.144] is blacklisted by ips.backscatterer.org"
msg="Host 85.Red-81-33-19.staticIP.rima-tde.net [81.33.19.85] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [5.251.101.182] is blacklisted by ips.backscatterer.org"
msg="Host m15-147.126.com [220.181.15.147] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [115.239.137.231] is blacklisted by ips.backscatterer.org"
msg="Host 119-46-184-50.static.asianet.co.th [119.46.184.50] is blacklisted by ips.backscatterer.org"
msg="Host 177-84-236-122.caiaponia.net.br [177.84.236.122] is blacklisted by ips.backscatterer.org"
msg="Host ip-95-87-44-82.trakiacable.bg [95.87.44.82] is blacklisted by ips.backscatterer.org"
msg="Host 68-185-134-150.dhcp.jcsn.tn.charter.com [68.185.134.150] is blacklisted by ips.backscatterer.org"
msg="Host m15-153.126.com [220.181.15.153] is blacklisted by ips.backscatterer.org"
msg="Host cpe-172-72-46-62.carolina.res.rr.com [172.72.46.62] is blacklisted by ips.backscatterer.org"
msg="Host cdm-75-108-105-103.asbnva.dhcp.suddenlink.net [75.108.105.103] is blacklisted by ips.backscatterer.org"
msg="Host m12-83.163.com [220.181.12.83] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [183.246.85.117] is blacklisted by ips.backscatterer.org"
msg="Host c915eadb.virtua.com.br [201.21.234.219] is blacklisted by ips.backscatterer.org"
msg="Host pool-46-63-105-53.x-city.ua [46.63.105.53] is blacklisted by ips.backscatterer.org"
msg="Host mm-68-192-122-178.brest.dynamic.pppoe.byfly.by [178.122.192.68] is blacklisted by ips.backscatterer.org"
msg="Host localhost [113.179.104.207] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [2.191.200.51] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [91.221.136.67] is blacklisted by ips.backscatterer.org"
msg="Host 190-51-61-214.speedy.com.ar [190.51.61.214] is blacklisted by ips.backscatterer.org"
msg="Host wsip-24-234-82-18.lv.lv.cox.net [24.234.82.18] is blacklisted by ips.backscatterer.org"
msg="Host mm-247-225-123-178.gomel.dynamic.pppoe.byfly.by [178.123.225.247] is blacklisted by ips.backscatterer.org"
msg="Host m15-147.126.com [220.181.15.147] is blacklisted by ips.backscatterer.org"
msg="Host DNSERROR [94.20.88.8] is blacklisted by ips.backscatterer.org"
msg="Host 77-45-112-151.sta.asta-net.com.pl [77.45.112.151] is blacklisted by ips.backscatterer.org"
`````

### CODE REVIEW

**Comment by msimerson** [comment]
I like it.

>  I've found it pretty safe to reject outright with.

I'd love to see a reject boolean added.

**Comment by smfreegard** [comment]
> I'd love to see a reject boolean added.

Why?  I can't see the point; add the plugin and let it reject - or intercept it's result via hook_deny and score it....

**Comment by msimerson** [comment]
> or intercept it's result via hook_deny

We've been over this. Intercepting at hook_deny and returning OK does let the connection continue but it causes other plugins on that hook to not get their turn.

**Comment by smfreegard** [comment]
Feel free to add it then.   It's not something that I currently have a use for as I don't use karma.

Maybe you should look into introducing a new constant that allows hook_deny to return something other than OK to continue running the hook.  Then adding reject options just to allow a plugin to work with karma would be totally unnecessary.

**Comment by baudehlo** [comment]
Didn't we add another return code for that?

**Comment by smfreegard** [comment]
Nope - you're thinking of the NEXT_HOOK constant I added to allow the HAProxy stuff to work

**Pull request merged**
