### PR TITLE
Fix early_talker to work at connect_init as well as data

### PR DESCRIPTION
**Pull request by smfreegard**

### CODE REVIEW

**Comment by baudehlo** [comment]
Lacks docs and tests (not sure it will be easy to test though)

**Comment by smfreegard** [comment]
Huh?  It's removing stuff from core that wasn't documented (and was dubious)?

**Comment by baudehlo** [comment]
Yes but we expect plugins to have docs.

**Comment by smfreegard** [comment]
Sorry - I misunderstood; I've updated the plugin docs to correctly match reality.

**Comment by baudehlo** [comment]
I feel bad for commenting now. I forgot this was already a plugin - I thought it was new. Mea culpa.

**Pull request closed without merging**
