### PR TITLE
Add license clause

### PR DESCRIPTION
**Pull request by Synchro**
Keeps npm quiet.

### CODE REVIEW

**Comment by Synchro** [comment]
Ah, I just spotted that npm complains because it has an old-style license that npm no longer supports, will correct.

**Comment by Dexus** [comment]
@Synchro please sqash it together thanks.

**Comment by Synchro** [comment]
I just did that and force-pushed - not sure why it kept the old commits.

**Comment by Dexus** [comment]
Git only adds live but cant remove old data live ;)

**Comment by Synchro** [comment]
Thanks

**Comment by Dexus** [comment]
NP

**Pull request merged**
