### PR TITLE
Kickout node-syslog …

### PR DESCRIPTION
**Pull request by Dexus**
…and strong-fork-syslog for modern-syslog (iojs compatible)

### CODE REVIEW

**Comment by msimerson** [comment]
When I apply this PR against my production server, install modern-syslog (cd node_modules/Haraka; npm install), and restart Haraka, I get no errors and also, no syslog output. Absolutely nothing. 

````
$ uname -prs
FreeBSD 10.1-RELEASE-p16 amd64
$ node -v
v0.10.40
````

This will require some more looking into.

**Comment by msimerson** [comment]
More info:

````
/Haraka/node_modules/modern-syslog $ npm test

> modern-syslog@1.1.0 test /usr/local/lib/node_modules/Haraka/node_modules/modern-syslog
> tap test/test-*.js

test/test-compat.js ................................... 8/8
test/test-core.js ................................... 14/14
test/test-openlog.js .June[44116]: Hi, June
Leonie: Hi, Leonie
test/test-openlog.js .................................. 1/1
test/test-setmask.js ................................ 32/32
test/test-stream.js ................................. 14/14
test/test-syslog.js ................................. 15/15
total ............................................... 84/84

  84 passing (1s)

  ok
````

**Comment by Dexus** [comment]
Hmm, absolute nothing?
I use it in production for an API and replace node-syslog 1:1 with modern-syslog without problems. Also my Haraka servers in production logging perfect. Is it a problem with FreeBSD?

**Comment by msimerson** [comment]
> Hmm, absolute nothing?

Correct.

> Is it a problem with FreeBSD?

Not sure yet.

**Comment by msimerson** [comment]
Update: modern-syslog is broken on FreeBSD. Worse, it doesn't complain, doesn't throw errors, it just does absolutely nothing. It probably doesn't work on Mac OS X or Windows either.

I expect that modern-syslog will get it working eventually and that we'll want to switch to it. In the meantime, perhaps a reasonable alternative is to have both strong-fork-syslog and modern-syslog installed as optionalDependencies and only load modern-syslog on Linux (until it's tested and working elsewhere)?

**Comment by Dexus** [comment]
yes, i think its the best solution.

**Comment by sam-github** [comment]
I've never used FreeBSD, what installable image would you recommend I use to repro this?

modern-syslog just calls `openlog()` and `syslog()`... its weird that it wouldn't work.

Does freebsd have the `logger` utility? Does it log? It could be that the system is not setup to log at modern-syslog's default log level and/or log facility.

**Comment by msimerson** [comment]
@sam-github , I install FreeBSD from [an ISO](ftp://ftp.freebsd.org/pub/FreeBSD/releases/ISO-IMAGES/10.2/FreeBSD-10.2-RELEASE-amd64-disc1.iso) onto physical hardware of VMware images alike. There are instructions for how to use pre-canned images for Amazon EC2, Google Compute Engine, and Azure on the [release](https://www.freebsd.org/releases/10.2R/announce.html) page and apparently it also installs in Docker as well.

````
[matt@storage] ~ % uname -a
FreeBSD storage.simerson.net 10.1-RELEASE-p16 FreeBSD 10.1-RELEASE-p16 #0: Tue Jul 28 12:04:19 UTC 2015     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
[matt@storage] ~ % logger 'test message'
[matt@storage] ~ % tail -n1 /var/log/messages
Sep 16 11:10:44 storage matt: test message

**Comment by trinitronx** [comment]
If `modern-syslog` turns out to be broken, there is also this PR out on `node-syslog` which has potential to fix support for `iojs` and `node.js` `4.0.0`: schamane/node-syslog#49

**Comment by sam-github** [comment]
So, I re-wrote node-syslog to work with v0.12, and I wrote modern-syslog because as much as we kept fixing node-syslog, I couldn't get publish rights for it. The code is essentially the same, there are basically 3 little functions that get wrapped.

Could someone link to where this project calls syslog, so I can see the use?

**Comment by baudehlo** [comment]
https://github.com/baudehlo/Haraka/blob/master/plugins/log.syslog.js

**Comment by rmg** [comment]
good news, there's also an official looking Vagrant box - https://atlas.hashicorp.com/freebsd

I'll see if I can repro this with it.

**Comment by rmg** [comment]
@msimerson if applying this to your production server results in total silence, doesn't that suggest it's actually strong-fork-syslog that is having issues? Otherwise an error message would have been spit out saying that it failed to load it before it trying modern-syslog.

**Comment by msimerson** [comment]
@rmg, the patch shown in this PR has evolved. When I tested, I did this:

````
cd /usr/local/lib/node_modules/Haraka
[matt@node] /usr/local/lib/node_modules/Haraka $ npm install modern-syslog
npm WARN package.json Haraka@2.6.1 No license field.
/
> modern-syslog@1.1.0 install /usr/local/lib/node_modules/Haraka/node_modules/modern-syslog
> node-gyp rebuild

gmake: Entering directory '/usr/local/lib/node_modules/Haraka/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
  SOLINK_MODULE(target) Release/obj.target/core.node
  COPY Release/core.node
gmake: Leaving directory '/usr/local/lib/node_modules/Haraka/node_modules/modern-syslog/build'
npm WARN unmet dependency /usr/local/lib/node_modules/Haraka/node_modules/express/node_modules/proxy-addr requires ipaddr.js@'0.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/Haraka/node_modules/ipaddr.js,
npm WARN unmet dependency which is version 1.0.3
modern-syslog@1.1.0 node_modules/modern-syslog
└── nan@2.0.9
````

and then updated log.syslog.js with this diff:
```diff
--- haraka.matt/plugins/log.syslog.js	2015-03-28 21:56:13.730162794 -0700
+++ plugins/log.syslog.js	2015-09-18 10:46:42.766128397 -0700
@@ -1,17 +1,16 @@
 'use strict';
 // log to syslog
 
-exports.register = function() {
+exports.register = function () {
     var plugin = this;
 
-    try { plugin.Syslog = require('node-syslog'); }
+    try { plugin.Syslog = require('modern-syslog'); }
     catch (e) {
-        plugin.logerror('failed to load node-syslog');
-
-        try { plugin.Syslog = require('strong-fork-syslog'); }
+        plugin.logerror('failed to load modern-syslog');
+        try { plugin.Syslog = require('node-syslog'); }
         catch (e) {
-            plugin.logerror("couldn't load strong-fork-syslog either");
-            plugin.logerror('try: npm i node-syslog strong-fork-syslog' );
+            plugin.logerror('failed to load node-syslog');
+            plugin.logerror('try: npm i node-syslog' );
             return;
         }
     }
```

After restarting Haraka, nothing is logged to /var/log/maillog (the default destination for MAIL facility on FreeBSD).

**Comment by rmg** [comment]
@msimerson thanks for the extra details. Did you check `/var/log/messages`? I've found a difference in how the per-message priorities are handled and I think that may be where your logs ended up.

**Comment by rmg** [comment]
An alternative to waiting for strongloop/modern-syslog#9 to be merged and released is to replace the giant switch statement in the middle of plugins/log.syslog.js with a single line:
```js
plugin.Syslog.init(name, options, 'LOG_' + facility.toUpperCase());
```

**Comment by Dexus** [comment]
@rmg :+1:  thanks.

**Comment by Dexus** [comment]
@msimerson PR updated.

**Pull request merged**
